//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONS.WEBPMO.Domain.Entities.Resources 
{
   
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SGIPMOMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SGIPMOMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ONS.SGIPMO.Domain.Entities.Resources.SGIPMOMessages", typeof(SGIPMOMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo &apos;{0}&apos; deve ser preenchido..
        /// </summary>
        public static string MS001 {
            get {
                return ResourceManager.GetString("MS001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um PMO configurado para o ano e mês informado..
        /// </summary>
        public static string MS002 {
            get {
                return ResourceManager.GetString("MS002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível incluir PMO para ano e mês menor que o atual..
        /// </summary>
        public static string MS003 {
            get {
                return ResourceManager.GetString("MS003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado nenhum registro com os parâmetros de pesquisa informados.
        /// </summary>
        public static string MS004 {
            get {
                return ResourceManager.GetString("MS004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo {0} está inválido..
        /// </summary>
        public static string MS005 {
            get {
                return ResourceManager.GetString("MS005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data {0} não pode ser menor que a data atual..
        /// </summary>
        public static string MS006 {
            get {
                return ResourceManager.GetString("MS006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um PMO deve ter ao menos uma(1) semana operativa..
        /// </summary>
        public static string MS007 {
            get {
                return ResourceManager.GetString("MS007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Só é possível abrir estudo para semana que ainda não passou por processo de configuração (que não possui gabarito associado)..
        /// </summary>
        public static string MS008 {
            get {
                return ResourceManager.GetString("MS008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de meses a frente do estudo não pode ser maior que 11 (onze)..
        /// </summary>
        public static string MS009 {
            get {
                return ResourceManager.GetString("MS009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível inserir ou excluir semana em PMO cuja data de início seja menor que a data atual..
        /// </summary>
        public static string MS010 {
            get {
                return ResourceManager.GetString("MS010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Só é possível excluir semana de PMO que ainda não foi aberta para estudo, ou que ainda esteja em configuração..
        /// </summary>
        public static string MS011 {
            get {
                return ResourceManager.GetString("MS011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso..
        /// </summary>
        public static string MS013 {
            get {
                return ResourceManager.GetString("MS013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados desta tela foram alterados por outro usuário. Acesse novamente para que sejam apresentados os dados atualizados..
        /// </summary>
        public static string MS014 {
            get {
                return ResourceManager.GetString("MS014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O gabarito já possui um registro de coleta para o insumo {0}, reservatório {1} e agente {2}..
        /// </summary>
        public static string MS015 {
            get {
                return ResourceManager.GetString("MS015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O insumo {0} já está configurado para ser informado pelo agente {1} para o reservatório {2}..
        /// </summary>
        public static string MS016 {
            get {
                return ResourceManager.GetString("MS016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione apenas um item para realização da operação..
        /// </summary>
        public static string MS017 {
            get {
                return ResourceManager.GetString("MS017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O gabarito já possui um registro de coleta para o insumo {0}, usina {1} e agente {2}..
        /// </summary>
        public static string MS018 {
            get {
                return ResourceManager.GetString("MS018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O insumo {0} já está configurado para ser informado pelo agente {1} para a usina {2}..
        /// </summary>
        public static string MS019 {
            get {
                return ResourceManager.GetString("MS019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O gabarito já possui um registro de coleta para o insumo {0}, subsistema {1} e agente {2}..
        /// </summary>
        public static string MS020 {
            get {
                return ResourceManager.GetString("MS020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O gabarito já possui um registro de coleta para o insumo {0}, contrato {1} e agente {2}..
        /// </summary>
        public static string MS021 {
            get {
                return ResourceManager.GetString("MS021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O gabarito já possui um registro de coleta para o insumo {0} e agente {1}..
        /// </summary>
        public static string MS022 {
            get {
                return ResourceManager.GetString("MS022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A operação não poderá ser realizada porque o estudo selecionado não está em processo de coleta de dados..
        /// </summary>
        public static string MS023 {
            get {
                return ResourceManager.GetString("MS023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A coleta do insumo selecionado ainda não foi enviada para análise do ONS..
        /// </summary>
        public static string MS024 {
            get {
                return ResourceManager.GetString("MS024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um item para realizar a operação..
        /// </summary>
        public static string MS025 {
            get {
                return ResourceManager.GetString("MS025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A coleta do insumo &apos;{0}&apos; do agente &apos;{1}&apos; não está disponível para captura. Observação: a captura pode ser realizada apenas para coletas que estejam nas situações: não iniciada, em andamento ou rejeitada..
        /// </summary>
        public static string MS026 {
            get {
                return ResourceManager.GetString("MS026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A coleta não pode ser encerrada porque ainda existem dados que não foram aprovados..
        /// </summary>
        public static string MS027 {
            get {
                return ResourceManager.GetString("MS027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção! Verifique a necessidade de alteração das datas de reunião e período de manutenção das outras semanas operativas..
        /// </summary>
        public static string MS028 {
            get {
                return ResourceManager.GetString("MS028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir PMO que contém semana que já tenha passado por processo de coleta de dados..
        /// </summary>
        public static string MS029 {
            get {
                return ResourceManager.GetString("MS029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir PMO que contém semana operativa com gabarito associado. Antes de excluir o PMO é necessário excluir as semanas operativas que possuem gabarito associado..
        /// </summary>
        public static string MS030 {
            get {
                return ResourceManager.GetString("MS030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A coleta de dados ainda não foi aberta para este estudo..
        /// </summary>
        public static string MS031 {
            get {
                return ResourceManager.GetString("MS031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso negado. Para informar dados de estudo é necessário autorização prévia do ONS..
        /// </summary>
        public static string MS032 {
            get {
                return ResourceManager.GetString("MS032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada nehuma intervenção programada para as usinas do agente..
        /// </summary>
        public static string MS033 {
            get {
                return ResourceManager.GetString("MS033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção já informada para o período..
        /// </summary>
        public static string MS034 {
            get {
                return ResourceManager.GetString("MS034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A coleta do insumo &apos;{0}&apos; do agente &apos;{1}&apos; não está disponível para envio. Observação: o envio pode ser realizado apenas para coletas que estejam nas situações: não iniciada, em andamento ou rejeitada..
        /// </summary>
        public static string MS035 {
            get {
                return ResourceManager.GetString("MS035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O insumo {0} não poder ser excluído porque está associado a item de gabarito de coleta..
        /// </summary>
        public static string MS036 {
            get {
                return ResourceManager.GetString("MS036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A grandeza &apos;{0}&apos; não poder ser excluída porque está associada a dado coletado de estudo..
        /// </summary>
        public static string MS037 {
            get {
                return ResourceManager.GetString("MS037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um insumo cadastrado com o nome informado..
        /// </summary>
        public static string MS038 {
            get {
                return ResourceManager.GetString("MS038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas grandezas numéricas podem receber valor negativo..
        /// </summary>
        public static string MS039 {
            get {
                return ResourceManager.GetString("MS039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível alterar ou excluir um insumo reservado do sistema..
        /// </summary>
        public static string MS042 {
            get {
                return ResourceManager.GetString("MS042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um ou mais itens para realizar a operação..
        /// </summary>
        public static string MS043 {
            get {
                return ResourceManager.GetString("MS043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ação não poderá ser realizada porque o estudo selecionado não está em processo de geração de blocos para montador..
        /// </summary>
        public static string MS046 {
            get {
                return ResourceManager.GetString("MS046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo de blocos para o montador já foi gerado. Para efetuar uma nova geração é necessário excluir a versão atual, reabrindo a coleta de dados do estudo..
        /// </summary>
        public static string MS047 {
            get {
                return ResourceManager.GetString("MS047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A coleta de dados não pode ser aberta para estudo que está em processo de convergência com CCEE. Aguarde o fim da convergência do PLD com a CCEE para realizar esta operação..
        /// </summary>
        public static string MS048 {
            get {
                return ResourceManager.GetString("MS048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta ação só pode ser realizada para estudo que está no estado/processo “Convergência CCEE” ou “PLD Convergido” ou “Publicado”..
        /// </summary>
        public static string MS049 {
            get {
                return ResourceManager.GetString("MS049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para realizar esta operação é necessário anexar ao menos um arquivo..
        /// </summary>
        public static string MS050 {
            get {
                return ResourceManager.GetString("MS050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está ação não poderá ser realizada porque o estudo selecionado não está em processo de convergência com CCEE..
        /// </summary>
        public static string MS051 {
            get {
                return ResourceManager.GetString("MS051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Só é possível resetar gabarito de semana de PMO que ainda esteja em configuração..
        /// </summary>
        public static string MS052 {
            get {
                return ResourceManager.GetString("MS052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção! O gabarito atual e dados coletados serão excluídos..
        /// </summary>
        public static string MS053 {
            get {
                return ResourceManager.GetString("MS053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O insumo já possui uma grandeza cadastrada com este nome..
        /// </summary>
        public static string MS054 {
            get {
                return ResourceManager.GetString("MS054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de dígitos informada para grandeza é maior que o máximo permitido &apos;{0}&apos;..
        /// </summary>
        public static string MS055 {
            get {
                return ResourceManager.GetString("MS055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de casas decimais informada para grandeza é maior que o máximo permitido &apos;{0}&apos;..
        /// </summary>
        public static string MS056 {
            get {
                return ResourceManager.GetString("MS056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção, a reabertura da coleta exclui todos os arquivos que tenham sido gerados e/ou anexados ao estudo! Confirma a abertura da coleta para o estudo?.
        /// </summary>
        public static string MS057 {
            get {
                return ResourceManager.GetString("MS057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível alterar gabarito de estudo que já passou por processo de coleta de dados.
        /// </summary>
        public static string MS059 {
            get {
                return ResourceManager.GetString("MS059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O insumo {0} já está configurado para ser informado pelo agente {1} para a unidade geradora {2}..
        /// </summary>
        public static string MS060 {
            get {
                return ResourceManager.GetString("MS060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A coleta do insumo &apos;{0}&apos; do agente &apos;{1}&apos; não está disponível para informar dados. Observação: esta operação só pode ser realizada apenas para coletas que estejam nas situações: não iniciada, em andamento, rejeitada ou informada..
        /// </summary>
        public static string MS061 {
            get {
                return ResourceManager.GetString("MS061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os valores {0} são inválidos para o tipo de dado {1}..
        /// </summary>
        public static string MS062 {
            get {
                return ResourceManager.GetString("MS062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção deve estar dentro do período de manutenções da semana operativa ({0} - {1}).
        /// </summary>
        public static string MS063 {
            get {
                return ResourceManager.GetString("MS063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insumo já associado a gabarito. Ao menos uma grandeza ativa deve ser informada..
        /// </summary>
        public static string MS064 {
            get {
                return ResourceManager.GetString("MS064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível inserir semana no início de PMO que já tenha passado por estudo..
        /// </summary>
        public static string MS065 {
            get {
                return ResourceManager.GetString("MS065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A operação não poderá ser realizada porque não existe nenhum insumo aprovado..
        /// </summary>
        public static string MS066 {
            get {
                return ResourceManager.GetString("MS066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso. A regra utilizada para a recuperação foi a seguinte: Para todos os estágios semanais do novo estudo, utilizar os dados declarados para o último estágio semanal do último estudo enviado. Para todos os estágios mensais do novo estudo, utilizar os dados declarados para o último estágio mensal do último estudo enviado..
        /// </summary>
        public static string MS067 {
            get {
                return ResourceManager.GetString("MS067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível exportar o Agente &apos;{0}&apos; / Insumo &apos;{1}&apos;, pois o mesmo não é do tipo Estruturado..
        /// </summary>
        public static string MS068 {
            get {
                return ResourceManager.GetString("MS068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(s) item(ns) selecionado(s) não tem permissão de exportação..
        /// </summary>
        public static string MS069 {
            get {
                return ResourceManager.GetString("MS069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um insumo cadastrado com a sigla informada..
        /// </summary>
        public static string MS070 {
            get {
                return ResourceManager.GetString("MS070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível aprovar o Agente &apos;{0}&apos; / Insumo &apos;{1}&apos;, pois o mesmo não se encontra nas situações: &quot;Não iniciado&quot; ou &quot;Pré-Aprovado&quot;..
        /// </summary>
        public static string MS071 {
            get {
                return ResourceManager.GetString("MS071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insumo(s) aprovado(s) com sucesso!.
        /// </summary>
        public static string MS072 {
            get {
                return ResourceManager.GetString("MS072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para realizar esta operação, os itens selecionados devem ser de um único Agente..
        /// </summary>
        public static string MS073 {
            get {
                return ResourceManager.GetString("MS073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A operação não poderá ser realizada porque o estudo selecionado não tem um processo específico..
        /// </summary>
        public static string MS074 {
            get {
                return ResourceManager.GetString("MS074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo {0} é obrigatório..
        /// </summary>
        public static string MS075 {
            get {
                return ResourceManager.GetString("MS075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O insumo &apos;{0}&apos; já foi aprovado pela ONS e, portanto, não pode ser alterado..
        /// </summary>
        public static string MS076 {
            get {
                return ResourceManager.GetString("MS076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente as empresas que ainda possuem informações a serem enviadas para o ONS serão notificadas..
        /// </summary>
        public static string MS078 {
            get {
                return ResourceManager.GetString("MS078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importação efetuada com sucesso..
        /// </summary>
        public static string MS079 {
            get {
                return ResourceManager.GetString("MS079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Volume informado para a Usina: {0} é o mesmo valor informado na semana anterior..
        /// </summary>
        public static string MS080 {
            get {
                return ResourceManager.GetString("MS080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os Volumes informados para as Usinas: {0} estão com os mesmos valores informados na semana anterior..
        /// </summary>
        public static string MS081 {
            get {
                return ResourceManager.GetString("MS081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Favor preencha o campo comentário para usina {0}..
        /// </summary>
        public static string MS082 {
            get {
                return ResourceManager.GetString("MS082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor informado para usina: {0} está fora da faixa de aceitação de 3% do valor de sugestão ({1}%) calculado pelo sistema. Para este caso é necessário preencher o campo comentário..
        /// </summary>
        public static string MS083 {
            get {
                return ResourceManager.GetString("MS083", resourceCulture);
            }
        }
    }
}
